name: wxGTK_Linux_x86_64

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'
  workflow_dispatch:
    branches: '*'

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v2
    - name: Install GNU 14 compiler suite, GTK3, wxWidgets
      run: |
        sudo apt update
        sudo apt install -y gcc-14 g++-14 libgtk-3-dev libwxgtk3.2-dev
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-14 110 --slave /usr/bin/g++ g++ /usr/bin/g++-14 --slave /usr/bin/gcov gcov /usr/bin/gcov-12
        uname -a
        wx-config --list
        wx-config --cxxflags
        wx-config --libs
        g++ --version | grep g++

    - name: Run CMake
      run: |
        cd build && ./cmLinux.sh && cd ..

    - name: Run GNU Make with GNU compiler
      run: |
        cd build/LinuxRelease && make && cd ../..
