name: wxOSX_x86_64

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'
  workflow_dispatch:
    branches: '*'

jobs:
  build:

    runs-on: macos-14

    steps:
    - uses: actions/checkout@v2
    - name: Install wxWidgets
      run: |
        curl -L http://www.libtiff.org/downloads/tiff-4.6.0t.tar.gz --output tiff-4.6.0t.tar.gz
        tar xzf tiff-4.6.0t.tar.gz
        cd tiff-4.6.0t
        ./configure
        make -j$(getconf _NPROCESSORS_ONLN)
        sudo make install
        cd ..
        curl -L https://github.com/wxWidgets/wxWidgets/releases/download/v3.2.5/wxWidgets-3.2.5.tar.bz2 --output wxWidgets-3.2.5.tar.bz2
        tar xjf wxWidgets-3.2.5.tar.bz2
        cd wxwidgets-3.2.5
        mkdir buildOSX
        cd buildOSX
        ../configure --enable-debug
        make -j$(getconf _NPROCESSORS_ONLN)
        sudo make install
        cd ../..
        #wx-config --list
        #wx-config --cxxflags
        #wx-config --libs
        #g++ --version | grep g++

    - name: Run CMake
      run: |
        cd build
        chmod +x ./cmAppleMac.sh
        ./cmAppleMac.sh
        cd ..

    - name: Run GNU Make with GNU compiler
      run: |
        cd build
        mkdir -p bin
        mkdir -p bin/Debug
        cd Mac
        make -j$(getconf _NPROCESSORS_ONLN)
        cd ../..
        cp wxWidgets-3.2.5/buildOSX/lib/*.dylib build/bin/Debug

    - uses: actions/upload-artifact@v2
      with:
        name: artifacts
        path: build/bin/Debug
